- name: Apt update
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name:
      - git
      - curl
      - wget
      - zip
      - unzip
      - p7zip-full
      - vim
      - nano
      - htop