- name: Install xorg
  become: true
  apt:
    name:
      - xorg

- name: Install DWM dependencies
  become: true
  apt:
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libx11-xcb-dev
      - libxcb-res0-dev

- name: Download DWM
  become: true
  git:
    repo: https://github.com/h3x0c4t/dwm-patched
    dest: /usr/local/src/dwm
    update: yes

- name: Run make clean install
  become: true
  command: make clean install
  args:
    chdir: /usr/local/src/dwm

- name: Install dmenu
  become: true
  apt:
    name:
      - dmenu

- name: Install dex
  become: true
  apt:
    name:
      - dex

- name: Check .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy user-dirs.dirs
  copy:
    src: user-dirs.dirs
    dest: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Copy .xinitrc
  copy:
    src: .xinitrc
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Download fonts
  become: true
  apt:
    name:
      - fontconfig
      - fonts-jetbrains-mono 
      - fonts-noto 
      - fonts-recommended

- name: Check .config/fontconfig directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy fonts.conf
  copy:
    src: fonts.conf
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/fonts.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Update font cache
  command: fc-cache -f