- name: Install xorg
  become: true
  apt:
    name:
      - xorg

- name: Install DWM dependencies
  become: true
  apt:
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libx11-xcb-dev
      - libxcb-res0-dev

- name: Download DWM
  become: true
  git:
    repo: https://github.com/h3x0c4t/dwm-patched
    dest: /usr/local/src/dwm
    update: yes

- name: Run make clean install
  become: true
  command: make clean install
  args:
    chdir: /usr/local/src/dwm

- name: Install dmenu
  become: true
  apt:
    name:
      - dmenu

- name: Install dex
  become: true
  apt:
    name:
      - dex

- name: Check .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy user-dirs.defaults
  become: true
  copy:
    src: user-dirs.defaults
    dest: /etc/xdg/user-dirs.defaults
    owner: root
    group: root
    mode: 0644

- name: Copy .xinitrc
  copy:
    src: .xinitrc
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Download fonts
  become: true
  apt:
    name:
      - fontconfig
      - fonts-jetbrains-mono 
      - fonts-noto 
      - fonts-recommended

- name: Check .config/fontconfig directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fontconfig"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy fonts.conf
  copy:
    src: fonts.conf
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/fonts.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Update font cache
  command: fc-cache -f

- name: Install icons
  become: true
  apt:
    name:
      - papirus-icon-theme

- name: Check .local/share/themes directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/themes"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Download themes
  become: true
  git:
    repo: https://github.com/EliverLara/Nordic
    dest: "{{ ansible_env.HOME }}/.local/share/themes/Nordic-darker-standard-buttons"
    version: darker-standard-buttons

- name: Check .config/gtk-3.0 directory
  file:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy settings.ini
  copy:
    src: settings.ini
    dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Install thunar
  become: true
  apt:
    name:
      - thunar
      - thunar-archive-plugin

- name: Check .config/Thunar directory
  file:
    path: "{{ ansible_env.HOME }}/.config/Thunar"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy uca.xml
  copy:
    src: uca.xml
    dest: "{{ ansible_env.HOME }}/.config/Thunar/uca.xml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
