- name: update apt cache
  become: true
  apt:
    update_cache: yes

- name: install packages
  become: true
  apt:
    state: latest
    name:
      - build-essential
      - git
      - curl
      - wget
      - zip
      - unzip
      - p7zip-full
      - neovim
      - nano
      - tmux
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - xorg
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libx11-xcb-dev
      - libxcb-res0-dev
      - libxkbcommon-x11-dev
      - dmenu
      - dex
      - fontconfig
      - fonts-jetbrains-mono 
      - fonts-noto 
      - fonts-recommended
      - papirus-icon-theme
      - alacritty
      - thunar
      - thunar-archive-plugin
      - firefox-esr
      - open-vm-tools-desktop
