- name: Apt update
  become: true
  apt:
    update_cache: yes

# Firefox
- name: Install packages
  become: true
  apt:
    name:
      - firefox-esr

- name: Configure firefox enterprise policy
  become: true
  shell: yes | unzip "{{ playbook_dir }}/roles/gui/files/enterprise_policy.zip" -d /usr/share/firefox-esr/

- name: Start firefox
  shell: |
    timeout 6 firefox
  ignore_errors: true

- name: Configure firefox profile
  shell: |
    cd ~/.mozilla/firefox/*.default-esr
    yes | rm -rf *
    yes | unzip "{{ playbook_dir }}/roles/gui/files/profile.zip" -d ~/.mozilla/firefox/*.default-esr/

# Codium
- name: Add key
  become: true
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: Add repository
  become: true
  apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    state: present
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name:
      - codium
