- name: srv13 base system installation
  hosts: localhost
  roles:
    - role: preinstall
      tags: preinstall
    - role: wm
      tags: wm
    - role: terminal
      tags: terminal
    - role: vboxguest
      tags: vboxguest
    - role: postinstall
      tags: postinstall
