- name: first start firefox
  shell: timeout 10 firefox-esr --headless
  ignore_errors: true

- name: check firefox config folder
  find:
    paths: "{{ ansible_env.HOME }}/.mozilla/firefox"
    patterns: '^.*\.default-esr'
    use_regex: true
    file_type: directory
  register: firefox_config_folder_search

- name: set firefox folder name as fact
  set_fact:
    firefox_config_folder_path: "{{ firefox_config_folder_search.files[0].path }}"

- name: Add in Firefox config
  copy:
    src: files/firefox/user.js
    dest: "{{ firefox_config_folder_path }}/user.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  when: firefox_config_folder_path != 'false'