- name: copy /etc/xdg/user-dirs.defaults
  become: true
  copy:
    src: user-dirs.defaults
    dest: /etc/xdg/user-dirs.defaults
    owner: root
    group: root
    mode: 0644

- name: update /etc/fstab
  become: true
  lineinfile:
    path: /etc/fstab
    line: .host:/    /mnt/hgfs    fuse.vmhgfs-fuse    defaults,allow_other    0    0

- name: copy nm-applet.desktop
  become: true
  copy:
    src: nm-applet.desktop
    dest: /etc/xdg/autostart/nm-applet.desktop
    owner: root
    group: root
    mode: 0644

- name: create home folders 1
  file:
    path: "{{ ansible_env.HOME }}/10-Tools"
    state: directory

- name: create home folders 2
  file:
    path: "{{ ansible_env.HOME }}/20-Data"
    state: directory

- name: create home folders 3
  file:
    path: "{{ ansible_env.HOME }}/30-Share"
    state: directory

- name: install network packages
  become: true
  apt:
    state: latest
    name:
      - network-manager
      - network-manager-gnome
      - network-manager-openvpn-gnome
      - systemd-resolved

- name: disable networking.service
  become: true
  systemd:
    name: networking.service
    enabled: no
    state: stopped

- name: enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: copy interfaces file
  become: true
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
