- name: create .~/config/alacritty directory
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    recurse: true

- name: copy alacritty.yml
  copy:
    src: alacritty.yml
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: copy .zshrc
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: Make zsh the default shell
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
