- name: gantsign.visual-studio-code
  include_role: 
    name: gantsign.visual-studio-code
    users:
    - username: "{{ ansible_env.USER }}" 
      visual_studio_code_extensions:
        - mads-hartmann.bash-ide-vscode
        - mhutchie.git-graph
