- name: Install Guest Additions dependencies
  become: true
  apt:
    name:
      - dkms

- name: Install VirtualBox Guest Additions
  become: true
  shell: |
    mkdir /mnt/cdrom
    mount /dev/cdrom /mnt/cdrom
    sh /mnt/cdrom/VBoxLinuxAdditions.run --nox11
    umount /mnt/cdrom
    rmdir /mnt/cdrom
    eject
  ignore_errors: true

- name: Add user to vboxsf group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: vboxsf
    append: yes

- name: Install NetworkManager
  become: true
  apt:
    name:
      - network-manager
      - network-manager-gnome

- name: Disable networking.service
  become: true
  systemd:
    name: networking.service
    enabled: no
    state: stopped

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Copy interfaces file
  become: true
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Copy nm-applet.desktop
  become: true
  copy:
    src: nm-applet.desktop
    dest: /etc/xdg/autostart/nm-applet.desktop
    owner: root
    group: root
    mode: 0644
