- name: Install vmware tools
  become: true
  apt:
    name: open-vm-tools-desktop

- name: Update /etc/fstab
  become: true
  lineinfile:
    path: /etc/fstab
    line: .host:/    /mnt/hgfs    fuse.vmhgfs-fuse    defaults,allow_other    0    0

- name: Install NetworkManager
  become: true
  apt:
    name:
      - network-manager
      - network-manager-gnome
      - network-manager-openvpn-gnome
      - systemd-resolved

- name: Disable networking.service
  become: true
  systemd:
    name: networking.service
    enabled: no
    state: stopped

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Copy interfaces file
  become: true
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Copy nm-applet.desktop
  become: true
  copy:
    src: nm-applet.desktop
    dest: /etc/xdg/autostart/nm-applet.desktop
    owner: root
    group: root
    mode: 0644

- name: Create home folders 1
  file:
    path: "{{ ansible_env.HOME }}/10-Tools"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Create home folders 2
  file:
    path: "{{ ansible_env.HOME }}/20-Data"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Create home folders 3
  file:
    path: "{{ ansible_env.HOME }}/30-Share"
    state: directory
    owner: "{{ ansible_env.USER }}"
