- name: Install evil-winrm
  become: true
  shell: gem install evil-winrm

- name: Fix /etc/ssl/openssl.cnf for evil-winrm
  become: true
  copy:
    src: openssl.cnf
    dest: /etc/ssl/openssl.cnf
    owner: root
    group: root
    mode: 0644