- name: Install dependency
  become: true
  apt:
    name:
      - libssl-dev

- name: Clone cliws
  git:
    repo: https://github.com/b23r0/cliws
    dest: /tmp/cliws
    force: yes

- name: Build cliws
  shell: |
    cd /tmp/cliws
    cargo build --release

- name: Create cliws folder
  file:
    path: "{{ ansible_env.HOME }}/10-Tools/cliws"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Move cliws to /usr/local/bin
  shell: cp /tmp/cliws/target/release/cliws ~/10-Tools/cliws/cliws

- name: Move cliws to /usr/local/bin
  become: true
  shell: mv /tmp/cliws/target/release/cliws /usr/local/bin/cliws

- name: Copy cliws exe
  copy:
    src: cliws.exe
    dest: "{{ ansible_env.HOME }}/10-Tools/cliws/cliws.exe"
    mode: 0755

- name: Clean up
  shell: rm -rf /tmp/cliws
