- name: Apt update
  become: true
  apt:
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name:
      - netdiscover # arp discovery
      - wireshark # packet sniffer
      - tshark # terminal version of wireshark
      