- name: create .~/config/tmux directory
  file:
    path: "{{ ansible_env.HOME }}/.config/tmux"
    state: directory
    recurse: true

- name: copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
