- name: Clone tun2socks
  git:
    repo: https://github.com/xjasonlyu/tun2socks
    dest: /tmp/tun2socks
    force: yes

- name: Build tun2socks
  ansible.builtin.shell: |
    cd /tmp/tun2socks
    make tun2socks

- name: Move tun2socks to /usr/local/bin
  become: true
  ansible.builtin.shell: |
    mv /tmp/tun2socks/build/tun2socks /usr/local/bin/tun2socks

- name: Clean up
  shell: rm -rf /tmp/tun2socks
