- name: Clone chisel
  git:
    repo: https://github.com/jpillora/chisel
    dest: /tmp/chisel
    force: yes

- name: Build chisel
  shell: |
    cd /tmp/chisel
    make BUILD="1337" VERSION="1337" linux
    make BUILD="1337" VERSION="1337" windows
    make BUILD="1337" VERSION="1337" darwin
    make BUILD="1337" VERSION="1337" freebsd

- name: Move chisel to /usr/local/bin
  become: true
  shell: mv /tmp/chisel/build/1337/1337/bin/chisel-linux_amd64 /usr/local/bin/chisel

- name: Create chisel folder
  file:
    path: "{{ ansible_env.HOME }}/10-Tools/chisel"
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Copy chisel binaries
  shell: |
    mv /tmp/chisel/build/1337/1337/bin/chisel-linux_amd64 "{{ ansible_env.HOME }}/10-Tools/chisel/chisel_lin"
    mv /tmp/chisel/build/1337/1337/bin/chisel-windows_amd64 "{{ ansible_env.HOME }}/10-Tools/chisel/chisel_win"
    mv /tmp/chisel/build/1337/1337/bin/chisel-darwin_amd64 "{{ ansible_env.HOME }}/10-Tools/chisel/chisel_osx"
    mv /tmp/chisel/build/1337/1337/bin/chisel-freebsd_amd64 "{{ ansible_env.HOME }}/10-Tools/chisel/chisel_bsd"

- name: Clean up
  shell: rm -rf /tmp/chisel
