- name: Install Guest Additions dependencies
  become: true
  apt:
    name:
      - dkms

- name: Install VirtualBox Guest Additions
  become: true
  shell: |
    mkdir /mnt/cdrom
    mount /dev/cdrom /mnt/cdrom
    sh /mnt/cdrom/VBoxLinuxAdditions.run --nox11
    umount /mnt/cdrom
    rmdir /mnt/cdrom
    eject
  ignore_errors: true

- name: Add user to vboxsf group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: vboxsf
    append: yes