- name: create ~/.config/fontconfig directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fontconfig"
    state: directory
    recurse: true

- name: copy fonts.conf
  copy:
    src: fonts.conf
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/fonts.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: update font cache
  shell: fc-cache -f
